/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("exercises_catalog")

  const poses = [
    // === WARMUP ===
    {
      name: "Ujjayi Pranayama",
      slug: "ujjayi-pranayama",
      description: "Respiración victoriosa. Inhala y exhala por la nariz con leve constricción en la garganta.",
      muscles: "diafragma,intercostales",
      category: "yoga",
      section: "warmup",
      is_timer: true,
      default_timer_seconds: 60,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Mantén la respiración audible y constante. 5 segundos inhala, 5 segundos exhala.",
    },
    {
      name: "Surya Namaskar A",
      slug: "surya-namaskar-a",
      description: "Saludo al Sol A. Secuencia dinámica de 9 posiciones sincronizadas con la respiración.",
      muscles: "cuerpo completo",
      category: "yoga",
      section: "warmup",
      is_timer: false,
      default_timer_seconds: 0,
      default_sets: 5,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Una respiración por movimiento. Salta o camina según tu nivel.",
    },
    {
      name: "Surya Namaskar B",
      slug: "surya-namaskar-b",
      description: "Saludo al Sol B. Secuencia más larga que incluye Utkatasana y Virabhadrasana I.",
      muscles: "cuerpo completo,cuádriceps,hombros",
      category: "yoga",
      section: "warmup",
      is_timer: false,
      default_timer_seconds: 0,
      default_sets: 3,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Añade Utkatasana al inicio y Virabhadrasana I en cada lado.",
    },

    // === STANDING SERIES ===
    {
      name: "Padangusthasana",
      slug: "padangusthasana",
      description: "Flexión de pie sujetando los dedos gordos. Estira isquiotibiales y espalda baja.",
      muscles: "isquiotibiales,espalda baja",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Sujeta los dedos gordos con índice y medio. Estira la espalda al inhalar, profundiza al exhalar.",
    },
    {
      name: "Padahastasana",
      slug: "padahastasana",
      description: "Flexión de pie con manos bajo los pies. Profundiza el estiramiento de isquiotibiales.",
      muscles: "isquiotibiales,muñecas",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Coloca las palmas bajo los pies. Flexiona las rodillas si es necesario.",
    },
    {
      name: "Utthita Trikonasana",
      slug: "utthita-trikonasana",
      description: "Triángulo extendido. Estira flancos, isquiotibiales y abre el pecho.",
      muscles: "oblicuos,isquiotibiales,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Piernas rectas, mano al tobillo o al suelo. Mira la mano de arriba.",
    },
    {
      name: "Parivrtta Trikonasana",
      slug: "parivrtta-trikonasana",
      description: "Triángulo en torsión. Rotación espinal profunda con estiramiento de isquiotibiales.",
      muscles: "oblicuos,isquiotibiales,columna",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Mano opuesta al pie adelantado. Rota desde el ombligo.",
    },
    {
      name: "Utthita Parsvakonasana",
      slug: "utthita-parsvakonasana",
      description: "Ángulo lateral extendido. Abre la cadera y estira el flanco.",
      muscles: "cadera,oblicuos,cuádriceps",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Rodilla a 90°, mano al suelo o al bloque.",
    },
    {
      name: "Parivrtta Parsvakonasana",
      slug: "parivrtta-parsvakonasana",
      description: "Ángulo lateral en torsión. Combina torsión espinal con apertura de cadera.",
      muscles: "cadera,oblicuos,columna",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Codo opuesto fuera de la rodilla. Gira el pecho al cielo.",
    },
    {
      name: "Prasarita Padottanasana A",
      slug: "prasarita-padottanasana-a",
      description: "Flexión con piernas separadas, variante A. Manos al suelo entre los pies.",
      muscles: "isquiotibiales,aductores",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Pies paralelos bien separados. Corona de la cabeza hacia el suelo.",
    },
    {
      name: "Prasarita Padottanasana B",
      slug: "prasarita-padottanasana-b",
      description: "Flexión con piernas separadas, variante B. Manos en la cintura.",
      muscles: "isquiotibiales,aductores",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Manos en la cintura, baja con la espalda recta.",
    },
    {
      name: "Prasarita Padottanasana C",
      slug: "prasarita-padottanasana-c",
      description: "Flexión con piernas separadas, variante C. Manos entrelazadas atrás.",
      muscles: "isquiotibiales,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Entrelaza las manos detrás, llévalas al suelo por encima de la cabeza.",
    },
    {
      name: "Prasarita Padottanasana D",
      slug: "prasarita-padottanasana-d",
      description: "Flexión con piernas separadas, variante D. Sujeta los dedos gordos.",
      muscles: "isquiotibiales,aductores",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Sujeta los dedos gordos con índice y medio, igual que Padangusthasana.",
    },
    {
      name: "Parsvottanasana",
      slug: "parsvottanasana",
      description: "Estiramiento lateral intenso. Flexión profunda sobre la pierna adelantada.",
      muscles: "isquiotibiales,espalda baja",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Manos en posición de oración inversa o al suelo.",
    },
    {
      name: "Utthita Hasta Padangusthasana",
      slug: "utthita-hasta-padangusthasana",
      description: "Mano al dedo gordo de pie. Equilibrio y flexibilidad de isquiotibiales.",
      muscles: "isquiotibiales,cadera,equilibrio",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Usa una correa si no llegas. Mantén la cadera nivelada.",
    },
    {
      name: "Ardha Baddha Padmottanasana",
      slug: "ardha-baddha-padmottanasana",
      description: "Medio loto de pie con flexión. Combina apertura de cadera con equilibrio.",
      muscles: "cadera,isquiotibiales,equilibrio",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Si no alcanzas medio loto, cruza el pie al muslo contrario.",
    },
    {
      name: "Utkatasana",
      slug: "utkatasana",
      description: "Postura de la silla. Fortalece cuádriceps y glúteos.",
      muscles: "cuádriceps,glúteos,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Rodillas juntas, brazos arriba. Peso en los talones.",
    },
    {
      name: "Virabhadrasana A",
      slug: "virabhadrasana-a",
      description: "Guerrero I. Fortalece piernas y abre la cadera.",
      muscles: "cuádriceps,glúteos,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Ambos lados. Rodilla delantera a 90°, cadera cuadrada al frente.",
    },
    {
      name: "Virabhadrasana B",
      slug: "virabhadrasana-b",
      description: "Guerrero II. Fortalece piernas y abre cadera lateralmente.",
      muscles: "cuádriceps,glúteos,aductores",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Brazos en línea, mirada sobre la mano delantera.",
    },

    // === SEATED SERIES ===
    {
      name: "Dandasana",
      slug: "dandasana",
      description: "Postura del bastón. Base sentada con piernas extendidas.",
      muscles: "core,espalda,cuádriceps",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Siéntate con las piernas extendidas, espalda recta, manos al lado de las caderas.",
    },
    {
      name: "Paschimottanasana A",
      slug: "paschimottanasana-a",
      description: "Flexión sentada hacia adelante, variante A. Estira toda la cadena posterior.",
      muscles: "isquiotibiales,espalda baja",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Sujeta los dedos gordos. Estira la espalda al inhalar, profundiza al exhalar.",
    },
    {
      name: "Paschimottanasana B",
      slug: "paschimottanasana-b",
      description: "Flexión sentada, variante B. Sujeta los lados de los pies.",
      muscles: "isquiotibiales,espalda baja",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Sujeta los lados de los pies. Estira la espalda al inhalar.",
    },
    {
      name: "Paschimottanasana C",
      slug: "paschimottanasana-c",
      description: "Flexión sentada, variante C. Sujeta las plantas de los pies.",
      muscles: "isquiotibiales,espalda baja",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Sujeta las plantas de los pies. La variante más profunda.",
    },
    {
      name: "Purvottanasana",
      slug: "purvottanasana",
      description: "Plancha invertida. Fortalece la cadena posterior y abre el pecho.",
      muscles: "glúteos,hombros,tríceps",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Eleva la cadera, pies planos al suelo. Mira al cielo o lleva la cabeza atrás.",
    },
    {
      name: "Ardha Baddha Padma Paschimottanasana",
      slug: "ardha-baddha-padma-paschimottanasana",
      description: "Medio loto sentado con flexión hacia adelante sobre la pierna extendida.",
      muscles: "isquiotibiales,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Pie en medio loto, flexiona sobre la pierna extendida.",
    },
    {
      name: "Triang Mukhaikapada Paschimottanasana",
      slug: "triang-mukhaikapada-paschimottanasana",
      description: "Una pierna doblada hacia atrás con flexión sobre la pierna extendida.",
      muscles: "isquiotibiales,cuádriceps,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Una pierna doblada atrás al lado de la cadera.",
    },
    {
      name: "Janu Sirsasana A",
      slug: "janu-sirsasana-a",
      description: "Cabeza a rodilla, variante A. Flexión sobre una pierna.",
      muscles: "isquiotibiales,espalda baja,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Pie al muslo interno contrario. Flexiona sobre la pierna extendida.",
    },
    {
      name: "Janu Sirsasana B",
      slug: "janu-sirsasana-b",
      description: "Cabeza a rodilla, variante B. Siéntate sobre el talón.",
      muscles: "isquiotibiales,cadera,tobillo",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Ambos lados. Siéntate sobre el talón, luego flexiona hacia adelante.",
    },
    {
      name: "Janu Sirsasana C",
      slug: "janu-sirsasana-c",
      description: "Cabeza a rodilla, variante C. Dedos del pie al suelo.",
      muscles: "isquiotibiales,cadera,tobillo",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Dedos del pie apuntan al suelo, talón arriba.",
    },
    {
      name: "Marichyasana A",
      slug: "marichyasana-a",
      description: "Torsión y flexión con una rodilla doblada.",
      muscles: "espalda baja,oblicuos,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Ambos lados. Rodilla doblada, brazo envuelve la espinilla. Enlaza las manos detrás.",
    },
    {
      name: "Marichyasana B",
      slug: "marichyasana-b",
      description: "Variante con medio loto y torsión.",
      muscles: "cadera,oblicuos,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Ambos lados. Medio loto + rodilla doblada, envuelve y enlaza.",
    },
    {
      name: "Marichyasana C",
      slug: "marichyasana-c",
      description: "Torsión profunda sentada.",
      muscles: "oblicuos,columna",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Ambos lados. Gira hacia la rodilla doblada, brazo opuesto por fuera.",
    },
    {
      name: "Marichyasana D",
      slug: "marichyasana-d",
      description: "Torsión profunda con medio loto.",
      muscles: "cadera,oblicuos,columna",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. La más desafiante de las Marichyasana. Usa correa si necesitas.",
    },
    {
      name: "Navasana",
      slug: "navasana",
      description: "Postura del barco. Fortalece el core profundo.",
      muscles: "core,flexores de cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 5,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "5 repeticiones. Levanta piernas y torso formando una V. Brazos paralelos al suelo.",
    },
    {
      name: "Bhujapidasana",
      slug: "bhujapidasana",
      description: "Presión de brazos. Equilibrio sobre las manos con piernas cruzadas.",
      muscles: "tríceps,core,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Apoya las manos entre las piernas, cruza los pies. Mantén el core activo.",
    },
    {
      name: "Kurmasana",
      slug: "kurmasana",
      description: "Postura de la tortuga. Flexión profunda con brazos extendidos bajo las piernas.",
      muscles: "isquiotibiales,espalda,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Piernas sobre los hombros, brazos bajo las piernas. Avanzada.",
    },
    {
      name: "Supta Kurmasana",
      slug: "supta-kurmasana",
      description: "Tortuga reclinada. Pies detrás de la cabeza.",
      muscles: "isquiotibiales,espalda,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Cruza los pies detrás de la cabeza, enlaza las manos. Modifica según necesites.",
    },
    {
      name: "Garbha Pindasana",
      slug: "garbha-pindasana",
      description: "Embrión en el vientre. Loto con brazos entre las piernas.",
      muscles: "cadera,core",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "En padmasana, pasa los brazos entre las piernas. Rueda en círculo.",
    },
    {
      name: "Kukkutasana",
      slug: "kukkutasana",
      description: "Postura del gallo. Equilibrio en loto sobre las manos.",
      muscles: "tríceps,core,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Desde Garbha Pindasana, presiona las manos al suelo y elévate.",
    },
    {
      name: "Baddha Konasana",
      slug: "baddha-konasana",
      description: "Postura del zapatero. Apertura profunda de cadera.",
      muscles: "cadera,aductores",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Plantas de los pies juntas, deja caer las rodillas. Flexiona hacia adelante.",
    },
    {
      name: "Upavishta Konasana",
      slug: "upavishta-konasana",
      description: "Ángulo sentado. Piernas abiertas con flexión hacia adelante.",
      muscles: "aductores,isquiotibiales",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Piernas bien abiertas, flexiona llevando el pecho al suelo.",
    },
    {
      name: "Supta Konasana",
      slug: "supta-konasana",
      description: "Ángulo reclinado. Piernas abiertas en inversión.",
      muscles: "aductores,isquiotibiales,core",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Rueda hacia atrás llevando los pies al suelo detrás de la cabeza, piernas abiertas.",
    },
    {
      name: "Supta Padangusthasana",
      slug: "supta-padangusthasana",
      description: "Mano al dedo gordo reclinado. Estiramiento de isquiotibiales boca arriba.",
      muscles: "isquiotibiales,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Ambos lados. Usa una correa si no llegas. Mantén la pierna contraria al suelo.",
    },
    {
      name: "Ubhaya Padangusthasana",
      slug: "ubhaya-padangusthasana",
      description: "Ambos dedos gordos. Equilibrio en V sentado.",
      muscles: "core,isquiotibiales",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Sujeta los dedos gordos, rueda hacia arriba y equilibra formando una V.",
    },
    {
      name: "Urdhva Mukha Paschimottanasana",
      slug: "urdhva-mukha-paschimottanasana",
      description: "Flexión hacia arriba. Piernas arriba con flexión profunda.",
      muscles: "isquiotibiales,core",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Desde la V, lleva las piernas más arriba acercando el pecho a los muslos.",
    },
    {
      name: "Setu Bandhasana",
      slug: "setu-bandhasana",
      description: "Puente. Eleva la cadera fortaleciendo glúteos y espalda.",
      muscles: "glúteos,espalda baja,cuádriceps",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "Corona de la cabeza al suelo, cruza los brazos sobre el pecho. Empuja con los pies.",
    },

    // === FINISHING SEQUENCE ===
    {
      name: "Urdhva Dhanurasana",
      slug: "urdhva-dhanurasana",
      description: "Rueda completa. Extensión profunda de espalda.",
      muscles: "espalda,hombros,cuádriceps,glúteos",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 3,
      default_reps: "1",
      default_rest_seconds: 5,
      note: "3 repeticiones. Manos y pies al suelo, empuja y eleva la cadera. Modifica con puente si necesitas.",
    },
    {
      name: "Salamba Sarvangasana",
      slug: "salamba-sarvangasana",
      description: "Vela con soporte. Inversión que calma el sistema nervioso.",
      muscles: "core,hombros,cuello",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 60,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Apoya los codos, manos en la espalda baja. Piernas rectas al cielo.",
    },
    {
      name: "Halasana",
      slug: "halasana",
      description: "Arado. Pies detrás de la cabeza desde la vela.",
      muscles: "isquiotibiales,espalda,cuello",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Desde Sarvangasana, baja los pies al suelo detrás de la cabeza.",
    },
    {
      name: "Karnapidasana",
      slug: "karnapidasana",
      description: "Presión en las orejas. Rodillas a las orejas desde el arado.",
      muscles: "espalda,cuello,isquiotibiales",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Desde Halasana, dobla las rodillas y llévalas a las orejas.",
    },
    {
      name: "Urdhva Padmasana",
      slug: "urdhva-padmasana",
      description: "Loto invertido. Padmasana en vela.",
      muscles: "core,cadera,hombros",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "En Sarvangasana, cruza las piernas en loto. Apoya las manos en las rodillas.",
    },
    {
      name: "Pindasana",
      slug: "pindasana",
      description: "Embrión en inversión. Loto invertido doblado.",
      muscles: "core,cadera",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Desde Urdhva Padmasana, baja las rodillas a la frente. Abraza las piernas.",
    },
    {
      name: "Matsyasana",
      slug: "matsyasana",
      description: "Postura del pez. Contrapostura a la vela, abre el pecho.",
      muscles: "pecho,cuello,espalda alta",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "En loto o piernas extendidas, arquea la espalda y apoya la corona en el suelo.",
    },
    {
      name: "Uttana Padasana",
      slug: "uttana-padasana",
      description: "Piernas extendidas elevadas. Variante de Matsyasana.",
      muscles: "core,cuádriceps,cuello",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Igual que Matsyasana pero con piernas elevadas a 45°. Brazos apuntando a los pies.",
    },
    {
      name: "Sirsasana",
      slug: "sirsasana",
      description: "Parada de cabeza. La reina de las posturas de yoga.",
      muscles: "hombros,core,equilibrio",
      category: "yoga",
      section: "main",
      is_timer: true,
      default_timer_seconds: 60,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 10,
      note: "Entrelaza los dedos, corona en el suelo. Sube lento. Usa la pared si necesitas.",
    },

    // === COOLDOWN ===
    {
      name: "Baddha Padmasana",
      slug: "baddha-padmasana",
      description: "Loto atado. Padmasana con brazos cruzados sujetando los pies.",
      muscles: "cadera,hombros",
      category: "yoga",
      section: "cooldown",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "En padmasana, cruza los brazos detrás y sujeta los pies. Flexiona si puedes.",
    },
    {
      name: "Yoga Mudra",
      slug: "yoga-mudra",
      description: "Sello de yoga. Flexión hacia adelante en padmasana.",
      muscles: "cadera,espalda",
      category: "yoga",
      section: "cooldown",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "En Baddha Padmasana, flexiona hacia adelante tocando la frente al suelo.",
    },
    {
      name: "Padmasana",
      slug: "padmasana-closing",
      description: "Loto sentado. Postura de meditación final.",
      muscles: "cadera",
      category: "yoga",
      section: "cooldown",
      is_timer: true,
      default_timer_seconds: 60,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Siéntate en loto o medio loto. Cierra los ojos, respira profundo.",
    },
    {
      name: "Utplutih",
      slug: "utplutih",
      description: "Elevación en loto. Levanta el cuerpo con las manos en loto.",
      muscles: "tríceps,hombros,core",
      category: "yoga",
      section: "cooldown",
      is_timer: true,
      default_timer_seconds: 30,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "En padmasana, manos al suelo, eleva todo el cuerpo. 10 respiraciones.",
    },
    {
      name: "Savasana",
      slug: "savasana",
      description: "Postura del cadáver. Relajación final profunda.",
      muscles: "cuerpo completo",
      category: "yoga",
      section: "cooldown",
      is_timer: true,
      default_timer_seconds: 300,
      default_sets: 1,
      default_reps: "1",
      default_rest_seconds: 0,
      note: "Cierra los ojos, relaja todo el cuerpo. Mínimo 5 minutos.",
    },
  ]

  for (const pose of poses) {
    // Idempotency: skip if slug already exists
    try {
      const existing = app.findFirstRecordByFilter("exercises_catalog", `slug = '${pose.slug}'`)
      if (existing) continue
    } catch (e) {
      // Not found — proceed to create
    }

    const record = new Record(collection)
    record.set("name", pose.name)
    record.set("slug", pose.slug)
    record.set("description", pose.description)
    record.set("muscles", pose.muscles)
    record.set("category", pose.category)
    record.set("is_timer", pose.is_timer)
    record.set("default_timer_seconds", pose.default_timer_seconds)
    record.set("default_sets", pose.default_sets)
    record.set("default_reps", pose.default_reps)
    record.set("default_rest_seconds", pose.default_rest_seconds || 0)
    record.set("note", pose.note)
    record.set("priority", "primary")
    record.set("status", "official")

    app.save(record)
  }
}, (app) => {
  // Down: remove all yoga catalog entries
  const records = app.findRecordsByFilter("exercises_catalog", "category = 'yoga'")
  for (const record of records) {
    app.delete(record)
  }
})
