import type { MCPServer } from "mcp-use/server";
import { z } from "zod";
import { getAuthManager } from "../mcpuse/auth-bridge.js";
import { errorResult, ResponseFormat } from "../utils.js";
import { normalizeName } from "../api/receipt-sanitizer.js";
import { PANTRY_UNITS } from "../api/schemas.js";

// Shape mirrors packages/core/types/pantry.ts `Recipe` — mcp-server is outside
// the pnpm workspace and can't import it, so the input schema replicates it.
const RecipeIngredientInputSchema = z
  .object({
    name: z.string().describe("Ingredient name as used in the recipe"),
    name_normalized: z.string().describe("lowercase, accent-free"),
    qty: z.number().nullable().describe("Quantity the recipe uses; null if 'to taste'"),
    unit: z.enum(PANTRY_UNITS).nullable(),
    from: z.enum(["pantry", "buy"]).describe("'pantry' = already in the user's inventory; 'buy' = needs to be bought"),
  })
  .strict();

const RecipeInputSchema = z
  .object({
    steps: z.array(z.string()).min(1).describe("Preparation steps, in order"),
    ingredients: z.array(RecipeIngredientInputSchema),
    prep_minutes: z.number().nullable().describe("Prep time in minutes; null if unknown"),
    servings: z.number().nullable().optional().describe("Servings this recipe yields (usually 1)"),
    photo_query: z
      .string()
      .nullable()
      .optional()
      .describe("Simple English dish name for photo lookup, e.g. 'chicken rice'"),
  })
  .strict();

function mapSavedRecipe(r: Record<string, unknown>) {
  const recipe: any = r.recipe ?? {};
  return {
    id: String(r.id),
    label: String(r.label ?? ""),
    label_normalized: String(r.label_normalized ?? ""),
    recipe: { steps: [], ingredients: [], prep_minutes: null, ...recipe } as any,
    times_used: Number(r.times_used ?? 0),
    created: r.created,
    updated: r.updated,
  };
}

export function registerRecipeTools(server: MCPServer, pbUrl: string) {
  // ──────────────────────────────────────────────────────────────
  // LIST SAVED RECIPES
  // ──────────────────────────────────────────────────────────────
  server.tool(
    {
      name: "cal_list_saved_recipes",
      title: "List Saved Recipes",
      description: "List the user's saved favorite recipes, most recent first.",
      schema: z
        .object({
          response_format: z
            .nativeEnum(ResponseFormat)
            .default(ResponseFormat.MARKDOWN)
            .describe("Output format"),
        })
        .strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async ({ response_format }, ctx) => {
      try {
        const auth = getAuthManager(ctx.auth, pbUrl);
        const pb = auth.getClient();
        const userId = auth.getUserId();

        const records = await pb.collection("saved_recipes").getFullList({
          filter: pb.filter("user = {:uid}", { uid: userId }),
          sort: "-created",
          requestKey: null,
        });
        const recipes = records.map(mapSavedRecipe);

        let text: string;
        if (response_format === ResponseFormat.JSON) {
          text = JSON.stringify(recipes, null, 2);
        } else if (recipes.length === 0) {
          text = "No tienes recetas guardadas todavía.";
        } else {
          const lines = [`# Recetas guardadas (${recipes.length})`, ""];
          for (const r of recipes) {
            const servings = r.recipe.servings ? `, ${r.recipe.servings} porción(es)` : "";
            const prep = r.recipe.prep_minutes ? `, ${r.recipe.prep_minutes} min` : "";
            const used = r.times_used > 0 ? ` — usada ${r.times_used}×` : "";
            lines.push(
              `- **${r.label}** — ${r.recipe.ingredients?.length ?? 0} ingrediente(s)${servings}${prep}${used} (\`${r.id}\`)`
            );
          }
          text = lines.join("\n");
        }

        return { content: [{ type: "text", text }], structuredContent: { count: recipes.length, recipes } };
      } catch (err) {
        return errorResult(err instanceof Error ? err.message : String(err));
      }
    }
  );

  // ──────────────────────────────────────────────────────────────
  // SAVE RECIPE
  // ──────────────────────────────────────────────────────────────
  server.tool(
    {
      name: "cal_save_recipe",
      title: "Save Favorite Recipe",
      description:
        "Save a recipe (e.g. one generated by a pantry plan) as a favorite for quick reuse later. Fails if a recipe with the same name is already saved — use cal_delete_saved_recipe first to replace it.",
      schema: z
        .object({
          label: z.string().min(1).max(120).describe("Name to save the recipe under"),
          recipe: RecipeInputSchema,
        })
        .strict(),
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
    },
    async ({ label, recipe }, ctx) => {
      try {
        const auth = getAuthManager(ctx.auth, pbUrl);
        const pb = auth.getClient();
        const userId = auth.getUserId();

        const labelNormalized = normalizeName(label);
        const existing = await pb
          .collection("saved_recipes")
          .getFirstListItem(
            pb.filter("user = {:uid} && label_normalized = {:norm}", { uid: userId, norm: labelNormalized }),
            { requestKey: null }
          )
          .catch(() => null);
        if (existing) {
          return errorResult("Ya existe una receta guardada con ese nombre.");
        }

        let rec: Record<string, any>;
        try {
          rec = await pb.collection("saved_recipes").create({
            user: userId,
            label,
            label_normalized: labelNormalized,
            recipe,
            times_used: 0,
          });
        } catch (err: any) {
          // Carrera: dos guardados concurrentes con el mismo nombre chocan contra el
          // índice único (user, label_normalized) — mismo mensaje amable que el check previo.
          if (err?.status === 400) {
            return errorResult("Ya existe una receta guardada con ese nombre.");
          }
          throw err;
        }

        return {
          content: [{ type: "text", text: `Receta **${label}** guardada (\`${rec.id}\`).` }],
          structuredContent: mapSavedRecipe(rec),
        };
      } catch (err) {
        return errorResult(err instanceof Error ? err.message : String(err));
      }
    }
  );

  // ──────────────────────────────────────────────────────────────
  // DELETE SAVED RECIPE
  // ──────────────────────────────────────────────────────────────
  server.tool(
    {
      name: "cal_delete_saved_recipe",
      title: "Delete Saved Recipe",
      description: "Delete a saved favorite recipe.",
      schema: z
        .object({
          recipe_id: z.string().describe("saved_recipes record id"),
        })
        .strict(),
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
    },
    async ({ recipe_id }, ctx) => {
      try {
        const auth = getAuthManager(ctx.auth, pbUrl);
        const pb = auth.getClient();
        const userId = auth.getUserId();

        let rec: Record<string, any>;
        try {
          rec = await pb.collection("saved_recipes").getOne(recipe_id, { requestKey: null });
        } catch (err: any) {
          // 404 = ya borrada, no es error (mismo patrón que useDeleteSavedRecipe / useShoppingList).
          if (err?.status === 404) {
            return {
              content: [{ type: "text", text: "La receta ya no existe (posiblemente ya fue eliminada)." }],
              structuredContent: { deleted: true, recipe_id, already_gone: true },
            };
          }
          throw err;
        }
        // Defense in depth: saved_recipes viewRule already restricts to the
        // owner, but don't act on another user's recipe if that rule ever changes.
        if (rec.user !== userId) {
          return errorResult("Receta no encontrada.");
        }

        await pb.collection("saved_recipes").delete(recipe_id);

        return {
          content: [{ type: "text", text: `Receta \`${recipe_id}\` eliminada.` }],
          structuredContent: { deleted: true, recipe_id },
        };
      } catch (err) {
        return errorResult(err instanceof Error ? err.message : String(err));
      }
    }
  );
}
